Added interactivity to the app.
thisisolya/todo pull request #2
Opened 2021-07-07 15:46 UTC by thisisolya

2021-07-07 20:48 UTC, paleika requested changes

2021-07-07 20:48 UTC, paleika commented on src/TodoApp.js
> +      {tasks.length >=1 && <ReviewList tasks={tasks} setTasks={setTasks} / >}
You can check just `task.length`, cause 0 is a foolish value

2021-07-07 20:48 UTC, paleika commented on src/TodoInput.js
> +        setTasks([...tasks, { text: textInput, id: uuidv4(),  completed: isDone, }]);
You do not need tasks in this component, only the way to add one
Create a function to add task to the state which will call `setTasks()` so you don't have to pass unnecessary prop here

I can't understand what `isDone` state stands for, why do you use a state inside a state (instead of setting it to true/false for each task directly)

And seems like you don't use `setIsDone` in this component even now

2021-07-07 20:48 UTC, paleika commented on src/TodoInput.js
> +    const handleAddButton = (e) => {
This function's name tells me that it handles the process of adding some button somewhere, which is wrong
try to rename to reflect what action it handles

2021-07-07 20:48 UTC, paleika commented on src/TodoItem.js
> +    const deleteTask = () => {
instead of passing full state to the tiny component create a function to manipulate state in a parent component and pass it as a prop

2021-07-07 20:48 UTC, paleika commented on src/TodoItem.js
> +        setIsDone(!isDone)
You've created a variable `isDone` with a false initial value and copy it's value to the new tast on creation
So new tasks will have `completed` property "false"

When user clicks on the checkbox you change that variable (instead of changing task's property)
Task is still uncompleted, but from now on all new tasks is going to have `completed` property set to "true"

You should find this task's element it `tasks` array and chage it. You can't store each task's status in one single variable

2021-07-08 06:19 UTC, thisisolya commented on src/ReviewList.js
> +            <p>Total amount of tasks: {tasks.length}</p>
May I do this by saving the  task.length in a variable? How can I refer to the length of an array without mentioning its name?

2021-07-08 06:26 UTC, thisisolya commented on src/ReviewList.js
> +            <p>Total amount of tasks: {tasks.length}</p>
I think I got it! Sorry for the silly question:)

2021-07-08 15:57 UTC, paleika commented on src/TodoApp.js
> +  const addTask = (obj) => {
Use more specific names for the variables, so you could easily remember what does it mean in a few weeks

2021-07-08 15:57 UTC, paleika commented on src/TodoApp.js
> +  const changeStatus = (currentTask) => {
You don't need the whole `currentTask` object here, just an id.
You can use cuttent value when toggling it: `{ ...item, completed: !item.completed }`

2021-07-08 15:57 UTC, paleika commented on src/TodoApp.js
> +      {!tasks.length || <ReviewList tasks={tasks.length} setTasks={setTasks} />}
It's recommended to return foolish values when you render nothing, so you'd better use `&&`
additionally it will look more clear as you'll get rid of unnecessary negation
`tasks.length && <List />`

2021-07-08 15:57 UTC, paleika commented on src/TodoItem.js
> +        deleteTask(oneTask.id)
Can you make one function that will be reusable for "delete one" and "delete all" actions?

2021-07-08 15:57 UTC, paleika commented on src/TodoApp.js
> +      {!tasks.length || <ReviewList tasks={tasks.length} setTasks={setTasks} />}
You should call a property by it's meaning, so `tasks` doesn't fit

2021-07-09 10:26 UTC, paleika commented on src/TodoApp.js
> +      {tasksArray.length !== 0 && <Footer tasksArray={tasksArray.length} deleteTask={deleteTask} />}
Please name the props according to their meaning!
You pass length - so don't name prop as 'array'

2021-07-09 10:26 UTC, paleika commented on src/TodoApp.js
> +    (clickedId === "clear-all") ? (modifyTasksArray(tasksArray = [])) : modifyTasksArray(tasksArray.filter((clickedTask) => clickedId !== clickedTask.id))
You can pass 'undefined' instead of 'clear-all'
Simply call function without arguments

2021-07-09 10:26 UTC, paleika commented on src/TodoApp.js
> +  let [tasksArray, modifyTasksArray] = useState([]);
it's a convention that you call a method to modify state param named `xyz` as `setXyz`
You will not edit the result of the `useState()` function so use `const`

2021-07-09 10:47 UTC, paleika commented on src/TodoApp.js
> +    (clickedId === undefined) ? (modifyTasksArray([])) : modifyTasksArray(tasksArray.filter((clickedTask) => clickedId !== clickedTask.id))
undefined is a foolish value so just `clickedId ? ... : ...`

2021-07-09 12:03 UTC, paleika approved these changes

2021-07-09 12:09 UTC, merged